#!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          ssh_nfs_portmap 
 # Required-Start:    $all
 # Required-Stop:     $local_fs $network $named $time $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Description:       Script to do portmapping of ssh to nfs
 ### END INIT INFO


SCRIPT='ssh -fNv -L 3049:localhost:2049 suraj@192.168.0.102'
RUNAS=root
PIDFILE=/var/run/ssh_nfs_portmap.pid
LOGFILE=/var/log/ssh_nfs_portmap.log

start() {
    
    #Checking if service already running
    if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
       echo 'Service already running' >&2
       return 1
    fi

    echo 'Starting service…' >&2
    local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
    su -c "$CMD" $RUNAS > "$PIDFILE"
    echo 'Service started' >&2
}


stop() {
    if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
        echo 'Service not running' >&2
        return 1
    fi
  
    echo 'Stopping service…' >&2
    kill -9 -$(ps -o pgid= $(cat "$PIDFILE") | grep -o '[0-9]*')
    echo 'Service stopped' >&2
}


case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
